extends: 
  - "airbnb"
  - "prettier"
  - "prettier/react"
plugins:
  - "prettier"
env:
  es6: true
  node: true
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
globals:
  ga: true
rules:
  prettier/prettier: "error"
  no-underscore-dangle: 0
  
