extends: "airbnb"
env:
  es6: true
  node: true
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
globals:
  ga: true
rules:
  quotes: 0
  comma-dangle: 0
  react/jsx-indent: 0
  react/jsx-indent-props: 0
  react/jsx-closing-bracket-location: 0
  no-confusing-arrow: 0
  no-underscore-dangle: 0
  
